version: "3.9"
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  api:
    build: ./
    container_name: chatbot-api
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
      MODEL_NAME: mistral:7b
      SYSTEM_PROMPT: |
        You are a helpful, concise assistant. If you are unsure, ask for details.
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

volumes:
  ollama:
